<?php

/**
 *
 * knut7 Framework (http://framework.artphoweb.com/)
 * knut7 FW(tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2016.  knut7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.0
 */
use \FWAP\Helpers\Security\Session;
?>

<div class="col-sm-12">

    <section>
        <div class="container">
            <section>
                <div class="page-header btn-default text-center" id="contact">
                    <!--  <?php
                    foreach ($this->breadcrumbs as $key => $value) {

                        echo $value;
                    }
                    ?> -->
                </div> <!-- End Page Header -->
                <div class="row">
                    <div class="col-lg-8">
                        <h1>My Account</h1>

                        <?php if(Session::exist()){
                            if(Session::get('role') == 'owner' || Session::get('role')== 'admin' ){?>
                                <p><a href="<?php echo URL; ?>Dashboard/customers"> Ir para Admin Pagina</a></p>

                           <?php }
                            }?>
                        <p><a href="<?php echo URL; ?>InsertDadosForDenuncia/">File a Complaint
                            </a></p>
                        <p><a href="<?php echo URL; ?>Account/edit">Edit your account information</a></p>
                        <p><a href="<?php echo URL; ?>Account/password">Change your password</a></p>
                        <p><a href="<?php echo URL; ?>Account/imageUser">Update Your Photo picture</a></p>

                    </div>
                    <div class="col-lg-4">

                        <div class="row">
                            <div  class="col-lg-6">

                                <?php

                                 if (!empty($this->UserPhoto['path'])) {
                                     ?>
                                    <p><img  src="<?php echo URL . $this->UserPhoto['path']; ?>" 
                                             class="image img-responsive img-thumbnail" alt="<?php echo $this->UserPhoto['path']; ?>">
                                    </p>


                                            <a href="<?php echo URL; ?>account/deleteImage/<?php echo Session::get('ID'); ?>"  class="glyphicon glyphicon-remove" ></a>
                                            <?php


                                } else {
                                    echo "nao tem imagem";
                                }
                                ?>

                            </div>

                        </div>



                        <h3>Outras Informações</h3>
                        <p></p>
                    </div>
                </div>


            </section>





