<?php

/**
 *
 * knut7 Framework (http://framework.artphoweb.com/)
 * knut7 FW(tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2016.  knut7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.0
 */
use \FWAP\Helpers\Security\Session;
?>

<div class="col-sm-12">

    <section>
        <div class="container">
            <section>
                <div class="page-header btn-default text-center" id="contact">
                    <h2>Actualize Password <small> <?php echo Session::get('role'); ?></small></h2>
                </div> <!-- End Page Header -->
                <div class="row">


                    <div class="row">
                        <div class="col-lg-4">
                            <form  class="form-horizontal" name="perfil" method="post">


                                <!-- <div class="form-group">
                                    <label for="user-url" class="col-lg-2 control-label">Password Antiga</label>
                                    <div class="col-lg-10">
                                        <input type="password" class="form-control" value="" name="password2" id="user-url">
                                    </div>
                                </div>  -->

                                <div class="form-group">
                                    <label for="user-url" class="col-lg-2 control-label">Password</label>
                                    <div class="col-lg-10">
                                        <input type="password" class="form-control" value="" name="password" id="user-url">
                                        <br>
                                        <button class=" btn-default glyphicon glyphicon-refresh " onclick="updateUser(<?php echo $this->UserData['id']; ?>)" ></button>
                                    </div>

                                </div> 

                            </form>
                        </div>
                    </div>
            </section>


            <script>

                function updateUser(id) {


                    var password = $('form[name=perfil] input[name=password]')[0].value;
                    password = (password != "<?php echo $this->UserData['password'] ?>" && password != '') ? password : "<?php echo $this->UserData['password'] ?>";


                    $.ajax({
                        type: "post",
                        url: "<?php echo URL; ?>account/managePassword",
                        data: {id: id, password: password }
                    }).done(function (resposta) {
                        if (resposta == true) {
                            alert(" atualizado com sucesso");
                        }

                    });

                    alert("vc vai atualizar o usuario com o id:" + id);
                }


                $(function () {

                    $('.deletar').click(function (e) {
                        var c = confirm("Tens a certeza que quer deletar?");
                        if (c == false)
                            return false;

                    });

                });


            </script>


