
<div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center">
        <form action="<?php echo URL;?>Index/procurar" method="post" >
            <div class="form-group">
                <select  name="type" class="form-control form-control-lg">
                    <option>--</option>
                    <option value="carro">Carro</option>
                    <option value="pessoa">Pessoa</option>
                    <option value="crimes">crimes</option>
                </select>
            </div>
            <div class="form-group">
                <label for="formGroupExampleInput2"></label>
                <input type="text" name="valor" class="form-control tele"   id="formGroupExampleInput2" >
            </div>
            <input type="submit" placeholder="Procurar">
        </form>
    </div>