

<section class="banner-section">
</section>
<section class="post-content-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-md-9 col-sm-12 ">

            <?php foreach($this->carro as $key => $value) :
                    $status = $value['status'];
                    if($status == 'roubado' ) : ?>

                        <div class="col-2 float-md-right">
                            <h1 class="btn btn-danger"> <?php echo $status; ?></h1>
                        </div>
                        <?php endif;

                    if($status == 'legal' ) : ?>

                        <div class="col-2 float-md-right">
                            <h1 class="btn btn-success"> <?php echo $status; ?></h1>
                        </div>
                        <?php endif; ?>


                    <strong class="align-content-center"> Nome do Proprietario:</strong><small> <?php echo $value['nome']; ?></small>
                    <table class="table">
                        <thead class="thead-inverse">
                        <tr>
                            <th>Marca</th>
                            <th>Matricula</th>
                            <th>Chassi</th>
                            <th>Motor</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td><?php echo $value['carrNome']; ?></td>
                            <td><?php echo $value['Matricula']; ?></td>
                            <td><?php echo $value['Chassi']; ?></td>
                            <td><?php echo $value['Motor']; ?></td>
                        </tr>

                        </tbody>
                    </table>
                    <?php endforeach; ?>
                <div class="col-lg-4  col-md-4 col-sm-5 float-md-left">
                    <table class="table">
                        <thead class="thead-inverse">
                        <tr>
                            <th>Modelo</th>
                            <th>Cor</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td><?php echo $value['Modelo']; ?></td>
                            <td><?php echo $value['cor']; ?></td>
                        </tr>

                        </tbody>
                    </table>
                </div>
                <div class="col-lg-5  col-md-4 col-sm-5 float-md-left">
                    <table class="table">
                        <thead class="thead-inverse align-content-center">
                        <tr>
                            <th>Local do Roubo</th>
                                <th>Ou do Furto</th>
                        </tr>

                        </thead>
                        <tbody>
                        <tr>
                            <td class="table-info">Cidade</td>
                            <td class="table-success"><?php echo $value['cidade']; ?></td>

                        </tr>
                        <tr>
                            <td class="table-info">provincia</td>
                            <td class="table-success"><?php echo $value['provincia']; ?></td>

                        </tr>
                        <tr>
                            <td class="table-info">municipio</td>
                            <td class="table-success"><?php echo $value['municipio']; ?></td>

                        </tr>
                        <tr>
                            <td  class="table-info">Bairro</td>
                            <td class="table-success"><?php echo $value['bairro']; ?></td>
                        </tr>
                        <tr>
                            <td class="table-info">Rua</td>
                            <td class="table-success"><?php echo $value['rua']; ?></td>
                        </tr>
                        <tr>
                            <td class="table-info">Vila</td>
                            <td class="table-success"><?php echo $value['vila']; ?></td>

                        </tr>

                        </tbody>
                    </table>
                </div>

                <div class="col-lg-3  float-md-left">
                    <table class="table">
                        <thead class="thead-inverse align-content-center">
                        <tr>
                            <th>Data do Roubo ou Furto</th>
                        </tr>

                        </thead>
                        <tbody>
                        <tr>
                            <td class="table-success"><?php echo $value['carroData']; ?></td>

                        </tr>

                        </tbody>
                    </table>
                </div>

            </div>

                <div class="col-lg-3  col-md-3 col-sm-12">

                <div class="well">
                    <h4>IMAGENS DO CARRO</h4>
                </div>
                <div class="list-group">
            <?php foreach ($this->foto as $k => $image) :?>
    <img  class="image img-responsive img-thumbnail" src="<?php echo URL .$image['path']; ?>">
    <h4 class="list-group-item-heading"></h4> <p class="list-group-item-text">
    </p>
                    <?php endforeach; ?>
                   </div>
                <div class="well">

                </div>
            </div>
        </div>


    </div> <!-- /container -->
</section>