

<?php
/**
 * Created by PhpStorm.
 * User: artphotografie
 * Date: 2016/02/14
 * Time: 12:39 PM
 */
?>

<?php

/**
 *
 * Tinymce styple
 *
 * */
use \FWAP\Helpers\Utility\Assets;
use \FWAP\Library\Copyright\Copyright;
?>

    <div class="gmd">
  <!-- your countent -->
</div>
<div class="gmd gmd-1">
  <!-- your countent -->
</div>
<div class="gmd gmd-2">
  <!-- your countent -->
</div>
<div class="gmd gmd-3">
  <!-- your countent -->
</div>
<div class="gmd gmd-4">
  <!-- your countent -->
</div>
<div class="gmd gmd-5">
  <!-- your countent -->
</div>
    
<br/><br/>

<footer class="footer panel-footer text-center ">
    <?php echo  \FWAP\Helpers\Copyright\Copyright::copyright(2015, 'knut7 FRAMWORK'); ?>
</footer>

<script src="<?php echo URL; ?>Public/bootstrap-4/jQuery.js"></script>
<script src="<?php echo URL; ?>Public/bootstrap-4/js/bootstrap.min.js"></script>
<script src="<?php echo URL; ?>Public/bootstrap-4/js/bootstrap.js"></script>
<script src="<?php echo URL; ?>Public/tinymce/tinymce.min.js"></script>


</body>
</html>

