<?php
/**
 *
 * knut7 Framework (http://framework.artphoweb.com/)
 * knut7 FW(tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2016.  knut7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.0
 */
?>
<?php

use \FWAP\Helpers\Security\Session;
use \FWAP\Helpers\Utility\Assets;

?>
<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset="UTF-8">
        
        <?php  echo Assets::css([URL. "Public/bootstrap-4/css/bootstrap.css", DIR_FILE. "Public/css/style.css" ] ); ?>

    <?php
    if (isset($this->Js)) {
        foreach ($this->Js as $Js) {
            echo ' <script type="text/javascript" src="' . URL . DIR_FILE. 'view/' . $Js . '"></script>';
        }
    }
    ?>
        <script type="text/javascript" src="<?php echo URL; ?>Public/bootstrap-4/js/jquery-3.2.1.js"></script>

        </head>

    <body>

    <div class="container">
        <div class="row">


    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <a class="navbar-brand" href="#">Navbar</a>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="nav nav-pills">
                <li class="nav-item">
                    <a class="nav-link active" href="<?php echo URL;?>"><span class="hidden-xs-down">Home</span><span class="hidden-sm-up">TN</span></a>
                </li>

                <?php if(Session::exist()) : ?>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo URL;?>Account/Cpanel"><span class="hidden-xs-down">CPANEL</span><span class="hidden-sm-up">TN</span></a>
                </li>
                <?php endif;?>
                <li class="nav-item">
                    <a class="nav-link" href="#"><span class="hidden-xs-down">LongTabName</span><span class="hidden-sm-up">TN</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><span class="hidden-xs-down">LongTabName</span><span class="hidden-sm-up">TN</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><span class="hidden-xs-down">LongTabName</span><span class="hidden-sm-up">TN</span></a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
        </div>
    </div>
    <br><br><br><br>
