<?php
/**
 *
 * knut7 Framework (http://framework.artphoweb.com/)
 * knut7 FW(tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2016.  knut7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.0
 */
?>
<?php

use \FWAP\Helpers\Security\Session;
use \FWAP\Helpers\Utility\Assets;

?>
<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset="UTF-8">
        
        <?php  echo Assets::css([URL. "Public/bootstrap-4/css/bootstrap.css", DIR_FILE. "Public/css/style.css" ] ); ?>

    <?php
    if (isset($this->Js)) {
        foreach ($this->Js as $Js) {
            echo ' <script type="text/javascript" src="' . URL . 'view/' . $Js . '"></script>';
        }
    }
    ?>
      <?php echo Assets::js([ URL."Public/bootstrap/js/bootstrap.js", URL."Public/bootstrap/jQuery.js", URL."Public/bootstrap/js/bootstrap.min.js"] ); ?>
        </head>

    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-inverse navbar-fixed-top" id="navbar">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <p class="navbar-brand">knut7</p>
                </div><!-- End Navbar Header -->

                <div class="collapse navbar-collapse " id="navbar-collapse">


                    <div class="navbar-btn navbar-right  ">
                        <?php if (Session::exist()) : ?>
                            <?php Session::get('U_NAME'); ?>
                            <div  class="btn btn-info glyphicon glyphicon-align-center glyphicon-log-out"><a href="<?php echo URL;?>user/DestroySession"> Logaut</a></div>
                            <p class=" btn btn-info glyphicon glyphicon-user"><?php echo "\n" . Session::get('U_NAME'); ?></p>
                        <?php else : ?>
                            <a href="<?php echo URL; ?>user"><button id="closse" class="btn btn-info glyphicon glyphicon-align-center glyphicon-log-in"> Login</button></a>
                            <a href="<?php echo URL; ?>user/signUp"><button id="closse" class="btn btn-info glyphicon glyphicon-align-center glyphicon-">REGISTER</button></a>
                            <?php ?>
                        <?php endif; ?>

                    </div>
                    <ul class="nav navbar-nav" >
                        <li><a href="<?php echo URL; ?>index">HOME</a> </li>
                        <?php if (Session::exist()): ?>
                            <li class=""><a href="<?php echo URL; ?>account/cpanel">PAINEL</a> </li>
                            <!-- <li class=""><a href="<?php echo URL; ?>SearchUser">DADOS PESSOAIS</a></li> -->
                            <?php if (Session::get('role') == 'owner' || Session::get('role') == 'admin'): ?>
                            <?php endif; ?>

                        <?php endif; ?>
                        <li class=""><a href="<?php echo URL; ?>Categorias">MAIS</a> </li>
                        <li class=""><a href="<?php echo URL; ?>faq">FAQ</a> </li>

                    </ul>
                </div>
            </div><!-- End Conteiner -->
        </nav><!-- End Navbar -->

